#!/bin/bash
set -x

export ELK_VERSION=${ELK_VERSION:-8.6.0}
# export OSS="-oss"
export OSS=
export SHARE_DIR=${SHARE_DIR:-~/opt}

mkdir -p $SHARE_DIR
cd $SHARE_DIR

if [ ! -d $SHARE_DIR/elasticsearch-$ELK_VERSION ]; then
    curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch${OSS}-$ELK_VERSION-linux-x86_64.tar.gz | tar xz

fi
if [ ! -d $SHARE_DIR/kibana-$ELK_VERSION-linux-x86_64 ]; then
    curl https://artifacts.elastic.co/downloads/kibana/kibana${OSS}-$ELK_VERSION-linux-x86_64.tar.gz | tar xz
fi

ln -s elasticsearch-$ELK_VERSION elasticsearch
ln -s kibana-$ELK_VERSION* kibana

# if [ ! -d $SHARE_DIR/elastic-data/elastic-data ]; then
#     curl -LO https://github.com/d-one/NLPeasy-workshop/releases/download/v0.2/elastic-data.tar.gz && tar xzvf elastic-data.tar.gz
# fi

cd

if [ ! -f okc_enriched_demo.pickle ]; then
    curl -LO https://github.com/d-one/NLPeasy-workshop/releases/download/v0.2/okc_enriched_demo.pickle.tar.gz && tar xzvf okc_enriched_demo.pickle.tar.gz
fi


# mkdir bin
# ln -s $SHARE_DIR/elasticsearch/bin/elasticsearch bin/
# ln -s $SHARE_DIR/kibana/bin/kibana bin/

# python -m spacy download en_core_web_sm
python -m spacy download en_core_web_md
# python -m spacy download de_core_news_md

# pip install ./jupyter-server-proxy-1.5.1.tar.gz
# pip install nlpeasy
pip install git+https://github.com/d-one/nlpeasy

if [ ! -r "profiles.csv.zip" ]; then
    curl -LO https://github.com/rudeboybert/JSE_OkCupid/raw/master/profiles.csv.zip
fi

# let's try to get /lab as default path:
echo "c.NotebookApp.default_url = '/lab'" >> .jupyter/jupyter_notebook_config.py
echo "c.ServerApp.default_url = '/lab'" >> .jupyter/jupyter_server_config.py
