#!/bin/bash

export SHARE_DIR=${SHARE_DIR:-~/opt}

echo -Xms600m >> $SHARE_DIR/elasticsearch/config/jvm.options
echo -Xmx600m >> $SHARE_DIR/elasticsearch/config/jvm.options

# bin/elasticsearch -d
$SHARE_DIR/elasticsearch/bin/elasticsearch -d -p $SHARE_DIR/pid.elastic -E xpack.security.enabled=false 2>&1 > $SHARE_DIR/log_elastic.log & #-E path.data=$SHARE_DIR/elastic-data/elastic-data/ #-E index.number_of_replicas=0

echo server.basePath: "${JUPYTERHUB_SERVICE_PREFIX:-/}"kibana >> $SHARE_DIR/kibana/config/kibana.yml
$SHARE_DIR/kibana/bin/kibana --ops.cGroupOverrides.cpuPath=/ --ops.cGroupOverrides.cpuAcctPath=/ 2>&1 > $SHARE_DIR/log_kibana.log &

exec "$@"
